-- Seed default underwriting questionnaire template
INSERT INTO questionnaires (
    id, product_id, category, title, description, version, is_active
) VALUES (
    'quest_default_underwriting',
    NULL,
    'all',
    'Formulir Standar Pengajuan & Underwriting Digital',
    'Kuesioner 4 pilar OJK meliputi identitas, kapasitas finansial, riwayat medis, dan legalitas ahli waris.',
    1,
    TRUE
) ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    version = EXCLUDED.version,
    is_active = EXCLUDED.is_active;

-- Seed Questions
INSERT INTO questions (
    id, questionnaire_id, step_number, pillar_type, code, label, help_text,
    input_type, placeholder, order_index, validation_rules, options,
    parent_question_id, show_if_parent_value, affects_pricing_field, underwriting_rules, is_active
) VALUES
-- STEP 1: IDENTITAS DUKCAPIL
(
    'q_id_nik',
    'quest_default_underwriting',
    1,
    'identity_verified',
    'nik',
    'Nomor Induk Kependudukan (NIK e-KTP)',
    '16 digit NIK tertera pada kartu e-KTP fisik Anda',
    'text',
    'Contoh: 3201123456780001',
    1,
    '{"required": true, "min_length": 16, "max_length": 16, "pattern": "^[0-9]{16}$", "error_message": "NIK harus 16 digit angka"}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_id_full_name',
    'quest_default_underwriting',
    1,
    'identity_verified',
    'full_name',
    'Nama Lengkap (Sesuai e-KTP)',
    'Nama lengkap nasabah tanpa singkatan gelar',
    'text',
    'Contoh: Budi Santoso',
    2,
    '{"required": true, "min_length": 2, "max_length": 120}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_id_birth_date',
    'quest_default_underwriting',
    1,
    'identity_verified',
    'birth_date',
    'Tanggal Lahir',
    'Sesuai tanggal lahir pada e-KTP (usia 18 - 60 tahun)',
    'date',
    NULL,
    3,
    '{"required": true}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_id_gender',
    'quest_default_underwriting',
    1,
    'identity_verified',
    'gender',
    'Jenis Kelamin',
    NULL,
    'radio',
    NULL,
    4,
    '{"required": true}'::jsonb,
    '[{"value": "male", "label": "Pria", "multiplier": 1.05}, {"value": "female", "label": "Wanita", "multiplier": 1.0}]'::jsonb,
    NULL,
    NULL,
    'gender',
    '{}'::jsonb,
    TRUE
),
(
    'q_id_phone',
    'quest_default_underwriting',
    1,
    'identity_verified',
    'phone',
    'Nomor WhatsApp / Seluler Aktif',
    'Untuk pengiriman notifikasi polis & OTP autentikasi',
    'text',
    'Contoh: 081234567890',
    5,
    '{"required": true, "min_length": 7, "max_length": 32, "pattern": "^[0-9+ ]{7,32}$"}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_id_email',
    'quest_default_underwriting',
    1,
    'identity_verified',
    'email',
    'Alamat Email Korespondensi',
    'Dokumen e-Policy resmi akan dikirimkan ke alamat email ini',
    'text',
    'nama@domain.com',
    6,
    '{"required": true, "format": "email"}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),

-- STEP 2: FINANSIAL & DSR
(
    'q_fin_occupation',
    'quest_default_underwriting',
    2,
    'income_verified',
    'occupation',
    'Pekerjaan / Bidang Profesi',
    'Profesi utama sumber penghasilan rutin',
    'text',
    'Contoh: Software Engineer, Akuntan, Pegawai Swasta',
    1,
    '{"required": true, "min_length": 2}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_fin_occupation_class',
    'quest_default_underwriting',
    2,
    'income_verified',
    'occupation_class',
    'Kategori Risiko Pekerjaan',
    'Klasifikasi risiko lingkungan kerja sesuai regulasi aktuaria',
    'select',
    NULL,
    2,
    '{"required": true}'::jsonb,
    '[{"value": "low", "label": "Rendah (Pekerjaan Kantor / Non-Fisik)", "multiplier": 0.95}, {"value": "standard", "label": "Standar (Mobilitas Normal / Supervisi Lapangan)", "multiplier": 1.0}, {"value": "high", "label": "Tinggi (Operasional Alat Berat / Tambang / Lepas Pantai)", "multiplier": 1.25}]'::jsonb,
    NULL,
    NULL,
    'occupation_class',
    '{}'::jsonb,
    TRUE
),
(
    'q_fin_monthly_income',
    'quest_default_underwriting',
    2,
    'income_verified',
    'monthly_income',
    'Penghasilan Tetap Bulanan (Rp)',
    'Pendapatan rutin per bulan untuk dasar perhitungan Debt Service Ratio (DSR)',
    'currency',
    '0',
    3,
    '{"required": true, "min": 1000000}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_fin_monthly_expenses',
    'quest_default_underwriting',
    2,
    'income_verified',
    'monthly_expenses',
    'Rata-rata Pengeluaran Rutin Bulanan (Rp)',
    NULL,
    'currency',
    '0',
    4,
    '{"required": true, "min": 0}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_fin_existing_debts',
    'quest_default_underwriting',
    2,
    'income_verified',
    'existing_debts_monthly',
    'Total Cicilan Utang / Pinjaman Bulanan (Rp)',
    'Total cicilan KPR, kendaraan, atau pinjaman lain yang sedang berjalan',
    'currency',
    '0',
    5,
    '{"required": true, "min": 0}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),

-- STEP 3: SKRINING MEDIS & GAYA HIDUP
(
    'q_med_weight',
    'quest_default_underwriting',
    3,
    'medical_required',
    'weight_kg',
    'Berat Badan (kg)',
    NULL,
    'number',
    '65',
    1,
    '{"required": true, "min": 30, "max": 250}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_med_height',
    'quest_default_underwriting',
    3,
    'medical_required',
    'height_cm',
    'Tinggi Badan (cm)',
    NULL,
    'number',
    '170',
    2,
    '{"required": true, "min": 100, "max": 250}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_med_smoker',
    'quest_default_underwriting',
    3,
    'medical_required',
    'is_smoker',
    'Status Penggunaan Tembakau & Rokok',
    'Apakah Anda aktif merokok atau menggunakan rokok elektrik dalam 12 bulan terakhir?',
    'radio',
    NULL,
    3,
    '{"required": true}'::jsonb,
    '[{"value": "no", "label": "Bukan Perokok", "multiplier": 1.0}, {"value": "yes", "label": "Perokok Aktif", "multiplier": 1.25}]'::jsonb,
    NULL,
    NULL,
    'smoker',
    '{}'::jsonb,
    TRUE
),
(
    'q_med_critical_illness',
    'quest_default_underwriting',
    3,
    'medical_required',
    'has_critical_illness',
    'Riwayat Penyakit Kritis',
    'Pernahkah Anda didiagnosis mengidap kanker, serangan jantung, stroke, gagal ginjal, atau diabetes melitus?',
    'radio',
    NULL,
    4,
    '{"required": true}'::jsonb,
    '[{"value": "no", "label": "Tidak Pernah", "multiplier": 1.0}, {"value": "yes", "label": "Pernah", "multiplier": 1.30, "risk_impact": "high", "rfi_required": true}]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"flag_if": "yes", "pillar_status": "pending", "rfi_type": "Resume Medis Dokter Spesialis", "sets_health_risk": "high"}'::jsonb,
    TRUE
),
(
    'q_med_critical_illness_details',
    'quest_default_underwriting',
    3,
    'medical_required',
    'critical_illness_details',
    'Rincian Diagnosa & Tahun Terjadinya Penyakit Kritis',
    'Sebutkan nama penyakit, tahun diagnosa, dan penanganan medis yang dilakukan',
    'text',
    'Contoh: Diabetes Tipe 2 tahun 2023, pengobatan oral rutin',
    5,
    '{"required": true, "min_length": 5}'::jsonb,
    '[]'::jsonb,
    'q_med_critical_illness',
    '"yes"'::jsonb,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_med_hospitalization',
    'quest_default_underwriting',
    3,
    'medical_required',
    'has_hospitalization_2y',
    'Riwayat Rawat Inap (Opname) 2 Tahun Terakhir',
    'Apakah Anda pernah menjalani rawat inap di rumah sakit atau operasi bedah dalam kurun waktu 24 bulan terakhir?',
    'radio',
    NULL,
    6,
    '{"required": true}'::jsonb,
    '[{"value": "no", "label": "Tidak Pernah", "multiplier": 1.0}, {"value": "yes", "label": "Pernah", "multiplier": 1.20, "risk_impact": "high", "rfi_required": true}]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"flag_if": "yes", "pillar_status": "pending", "rfi_type": "Surat Keterangan Rawat Inap RS", "sets_health_risk": "high"}'::jsonb,
    TRUE
),
(
    'q_med_hospitalization_details',
    'quest_default_underwriting',
    3,
    'medical_required',
    'hospitalization_details',
    'Rincian Alasan Rawat Inap & Nama Rumah Sakit',
    'Sebutkan alasan tindakan medis, tanggal rawat, dan status kesembuhan saat ini',
    'text',
    'Contoh: Operasi usus buntu tahun 2025 di RS Siloam, rawat inap 3 hari, sembuh total',
    7,
    '{"required": true, "min_length": 5}'::jsonb,
    '[]'::jsonb,
    'q_med_hospitalization',
    '"yes"'::jsonb,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_med_family_history',
    'quest_default_underwriting',
    3,
    'medical_required',
    'has_family_history',
    'Riwayat Kesehatan Keluarga Keturunan',
    'Apakah ada orang tua atau saudara kandung yang meninggal atau terdiagnosa penyakit kritis sebelum usia 60 tahun?',
    'radio',
    NULL,
    8,
    '{"required": true}'::jsonb,
    '[{"value": "no", "label": "Tidak Ada"}, {"value": "yes", "label": "Ada"}]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),

-- STEP 4: LEGALITAS & AHLI WARIS
(
    'q_ben_name',
    'quest_default_underwriting',
    4,
    'documents_complete',
    'beneficiary_name',
    'Nama Lengkap Ahli Waris (Penerima Manfaat)',
    'Nama sesuai e-KTP penerima hak klaim pertanggungan',
    'text',
    'Contoh: Siti Rahayu',
    1,
    '{"required": true, "min_length": 2}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_ben_relationship',
    'quest_default_underwriting',
    4,
    'documents_complete',
    'beneficiary_relationship',
    'Hubungan Keluarga Ahli Waris dengan Tertanggung',
    'Hubungan kekeluargaan resmi yang memiliki kepentingan asuransi (insurable interest)',
    'select',
    NULL,
    2,
    '{"required": true}'::jsonb,
    '[{"value": "spouse", "label": "Suami / Istri Sah"}, {"value": "child", "label": "Anak Kandung"}, {"value": "parent", "label": "Orang Tua Kandung"}, {"value": "sibling", "label": "Saudara Kandung"}]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_ben_nik',
    'quest_default_underwriting',
    4,
    'documents_complete',
    'beneficiary_nik',
    'Nomor KTP / NIK Ahli Waris',
    'Nomor identitas kependudukan 16 digit penerima manfaat',
    'text',
    'Contoh: 3201123456780002',
    3,
    '{"required": true, "min_length": 16, "max_length": 16, "pattern": "^[0-9]{16}$"}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_ben_share',
    'quest_default_underwriting',
    4,
    'documents_complete',
    'beneficiary_share',
    'Alokasi Hak Manfaat Tunggal (%)',
    'Penerima manfaat tunggal berhak atas 100% uang pertanggungan',
    'number',
    '100',
    4,
    '{"required": true, "min": 100, "max": 100}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_legal_truth',
    'quest_default_underwriting',
    4,
    'documents_complete',
    'agree_truth_declaration',
    'Pernyataan Kebenaran Data Underwriting',
    'Saya menyatakan seluruh data identitas, profil finansial, dan deklarasi kesehatan di atas adalah benar dan sesuai kenyataan sesungguhnya. Data akan divalidasi langsung oleh sistem underwriting resmi.',
    'checkbox',
    NULL,
    5,
    '{"required": true}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
),
(
    'q_legal_terms',
    'quest_default_underwriting',
    4,
    'documents_complete',
    'agree_policy_terms',
    'Persetujuan Klausul & Syarat Ketentuan Polis Resmi',
    'Saya telah membaca, memahami, dan menyetujui seluruh Ketentuan Polis, klausul pengecualian, masa tunggu, serta proses peninjauan pengajuan underwriting digital.',
    'checkbox',
    NULL,
    6,
    '{"required": true}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    '{}'::jsonb,
    TRUE
)
ON CONFLICT (id) DO UPDATE SET
    label = EXCLUDED.label,
    help_text = EXCLUDED.help_text,
    input_type = EXCLUDED.input_type,
    placeholder = EXCLUDED.placeholder,
    order_index = EXCLUDED.order_index,
    validation_rules = EXCLUDED.validation_rules,
    options = EXCLUDED.options,
    parent_question_id = EXCLUDED.parent_question_id,
    show_if_parent_value = EXCLUDED.show_if_parent_value,
    affects_pricing_field = EXCLUDED.affects_pricing_field,
    underwriting_rules = EXCLUDED.underwriting_rules,
    is_active = EXCLUDED.is_active;
