ALTER TABLE products ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'active';
ALTER TABLE products ADD COLUMN IF NOT EXISTS non_mcu_limit BIGINT NOT NULL DEFAULT 500000000;
CREATE INDEX IF NOT EXISTS idx_products_status ON products(status);
